name: sauna_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  social_login_buttons: ^1.0.7
  table_calendar: ^3.0.8
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.3
  flutter_riverpod: ^2.1.3
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  intl: ^0.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

