name: sauna_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  social_login_buttons: ^1.0.7
  table_calendar: ^3.0.8
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.3
  flutter_riverpod: ^2.1.3
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  intl: ^0.17.0
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.2.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_ios: "lib/assets/icon.png"
  image_path_android: "lib/assets/icon_android.png"
  adaptive_icon_background: "FF5757"

flutter_native_splash:
  image: "lib/assets/icon.png"
  color: "FF5757"
  fullscreen: true
  icon_background_color: "FF5757"
